#!/usr/bin/env python3
"""Token-efficiency analysis of the pi-unified-edit 'four' A/B run.

Reads the per-run pi session stores produced by the edit-ab E-pack runner
(`run_four_modes.sh` / `run_all.sh` in the repo's local_data/edit-ab
directory) and aggregates the per-message `usage` records into
per-mode/per-model token and cost statistics.

Each A/B run launches pi with `--session-dir <workdir>/.pi-session`, so every
run directory contains one JSONL session store; every assistant message in it
carries a `usage` block (input/output/cacheRead/cacheWrite/reasoning/
totalTokens/cost). This script sums those records per case and compares the
four edit dialects (rows/patch/code/pi).

Usage:
    python3 scripts/analyze_tokens.py                 # default runs dir
    EDITAB_RUNS=/path/to/runs python3 scripts/analyze_tokens.py

The default runs dir resolves to <repo-root>/local_data/edit-ab/runs
(gitignored scratch, generated by the edit-ab case pack; see IV-0022).
"""
import json, glob, os, re, sys, statistics
from collections import defaultdict

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "..", ".."))
RUNS = os.environ.get(
    "EDITAB_RUNS",
    os.path.join(_REPO_ROOT, "local_data", "edit-ab", "runs"),
)
MODES = ["rows", "patch", "code", "pi"]
MODEL_SHORT = {
    "opencode-go_deepseek-v4-flash_max": "ds",
    "openai-codex_gpt-5_6-sol_high": "sol",
    "openai-codex_gpt-5_6-luna_max": "luna",
    "fluxion-claude_claude-opus-5_high": "opus",
}

def parse_run(workdir):
    """Return dict of summed usage + edit call count for one run dir."""
    sess = glob.glob(os.path.join(workdir, ".pi-session", "*.jsonl"))
    if not sess:
        return None
    agg = defaultdict(int)
    edit_calls = 0
    read_calls = 0
    msgs_no_usage = 0
    n_asst = 0
    with open(sess[0]) as fh:
        for line in fh:
            obj = json.loads(line)
            if obj.get("type") != "message":
                continue
            m = obj["message"]
            if m.get("role") == "assistant":
                n_asst += 1
                u = m.get("usage")
                if not u:
                    msgs_no_usage += 1
                    continue
                for k in ("input", "output", "cacheRead", "cacheWrite", "reasoning", "totalTokens"):
                    agg[k] += u.get(k, 0)
                c = u.get("cost") or {}
                agg["cost"] += c.get("total", 0)
                for part in m.get("content", []):
                    if part.get("type") == "tool_use" or ("name" in part and "arguments" in part):
                        if part.get("name") == "edit":
                            edit_calls += 1
                        if part.get("name") in ("read", "grep", "ls", "bash", "exec_command", "view"):
                            read_calls += 1
    agg["edit_calls"] = edit_calls
    agg["read_calls"] = read_calls
    agg["msgs_no_usage"] = msgs_no_usage
    agg["n_asst"] = n_asst
    return agg

def run_info(workdir):
    base = os.path.basename(workdir)[:-len("-workdir")]
    # 20260813-094553-e1-basic-opencode-go_deepseek-v4-flash_max-four-patch
    m = re.match(r"^\d+-\d+-(e\d+-\w+)-(.+)-four-(rows|patch|code|pi)$", base)
    return m.groups() if m else (None, base, None)

# Collect per (model, mode): list of per-case token totals
data = defaultdict(list)   # (model, mode) -> [per-case dicts]
for d in sorted(glob.glob(os.path.join(RUNS, "*-four-*-workdir"))):
    case, ident, mode = run_info(d)
    if mode not in MODES:
        continue
    model = None
    for k, v in MODEL_SHORT.items():
        if k in ident:
            model = v
            break
    if model is None:
        print("UNKNOWN model:", ident); continue
    agg = parse_run(d)
    if agg is None:
        print("NO SESSION:", ident, f"({case})"); continue
    agg["case"] = case
    data[(model, mode)].append(agg)

def fmt_mean_median(vals):
    if not vals:
        return "n/a"
    return f"mean {statistics.mean(vals):>10,.0f}  median {statistics.median(vals):>10,.0f}"

def fmt_cost(vals):
    if not vals:
        return "n/a"
    return f"mean {statistics.mean(vals):>10.4f}  median {statistics.median(vals):>10.4f}"

# ---- 1. Per-mode x per-model: total tokens per case ----
print("=" * 100)
print("TOTAL TOKENS PER CASE (usage.totalTokens summed over assistant messages)")
print("=" * 100)
hdr = f"{'model':<6}" + "".join(f"{m:>30}" for m in MODES)
print(hdr)
for model in ["ds", "sol", "luna", "opus"]:
    row = f"{model:<6}"
    for mode in MODES:
        vals = [a["totalTokens"] for a in data[(model, mode)]]
        row += f"{fmt_mean_median(vals):>30}"
    print(row)
print()
print("ALL MODELS COMBINED:")
row = f"{'ALL':<6}"
for mode in MODES:
    vals = [a["totalTokens"] for md in ["ds", "sol", "luna", "opus"] for a in data[(md, mode)]]
    row += f"{fmt_mean_median(vals):>30}"
print(row)

# ---- 2. Cost per case ----
print()
print("=" * 100)
print("COST PER CASE (USD, from usage.cost.total)")
print("=" * 100)
print(hdr)
for model in ["ds", "sol", "luna", "opus"]:
    row = f"{model:<6}"
    for mode in MODES:
        vals = [a["cost"] for a in data[(model, mode)]]
        row += f"{fmt_cost(vals):>30}"
    print(row)
print()
row = f"{'ALL':<6}"
for mode in MODES:
    vals = [a["cost"] for md in ["ds", "sol", "luna", "opus"] for a in data[(md, mode)]]
    row += f"{fmt_cost(vals):>30}"
print(row)

# ---- 3. First-try-only token efficiency (edit_calls == 1) ----
print()
print("=" * 100)
print("FIRST-TRY CASES ONLY (edit_calls == 1): mean totalTokens per case  [n cases]")
print("=" * 100)
print(hdr)
for model in ["ds", "sol", "luna", "opus"]:
    row = f"{model:<6}"
    for mode in MODES:
        vals = [a["totalTokens"] for a in data[(model, mode)] if a["edit_calls"] == 1]
        n = len(vals)
        row += f"{fmt_mean_median(vals) + f'  [n={n}]':>30}"
    print(row)
print()
row = f"{'ALL':<6}"
for mode in MODES:
    vals = [a["totalTokens"] for md in ["ds", "sol", "luna", "opus"] for a in data[(md, mode)] if a["edit_calls"] == 1]
    n = len(vals)
    row += f"{fmt_mean_median(vals) + f'  [n={n}]':>30}"
print(row)

# ---- 4. Input/output/reasoning breakdown per mode (all models) ----
print()
print("=" * 100)
print("TOKEN BREAKDOWN PER MODE (all models, summed across cases)")
print("=" * 100)
print(f"{'mode':<8}{'input':>14}{'output':>14}{'reasoning':>14}{'cacheRead':>14}{'TOTAL':>14}{'cost $':>12}")
for mode in MODES:
    agg = defaultdict(int)
    for model in ["ds", "sol", "luna", "opus"]:
        for a in data[(model, mode)]:
            for k in ("input", "output", "reasoning", "cacheRead", "totalTokens", "cost"):
                agg[k] += a[k]
    print(f"{mode:<8}{agg['input']:>14,}{agg['output']:>14,}{agg['reasoning']:>14,}{agg['cacheRead']:>14,}{agg['totalTokens']:>14,}{agg['cost']:>12.4f}")

# ---- 5. Retry profile per mode (all models) ----
print()
print("=" * 100)
print("EDIT-CALL DISTRIBUTION PER MODE (all models)")
print("=" * 100)
print(f"{'mode':<8}{'edit calls':>12}{'1-try cases':>14}{'2-try':>10}{'3+ tries':>12}{'max retries':>14}")
for mode in MODES:
    calls = [a["edit_calls"] for a in data[(model, mode)] for model in ["ds", "sol", "luna", "opus"]]
    n1 = sum(1 for c in calls if c == 1)
    n2 = sum(1 for c in calls if c == 2)
    n3 = sum(1 for c in calls if c >= 3)
    print(f"{mode:<8}{sum(calls):>12,}{n1:>14}{n2:>10}{n3:>12}{max(calls) if calls else 0:>14}")

# ---- 5b. Turns and per-turn context size (all models) ----
print()
print("=" * 100)
print("TURNS PER CASE & CONTEXT PER TURN (all models)")
print("=" * 100)
print(f"{'mode':<8}{'turns/case mean':>18}{'input/turn mean':>18}{'output/turn mean':>18}{'reasoning/turn':>16}")
for mode in MODES:
    runs_all = [a for md in ["ds", "sol", "luna", "opus"] for a in data[(md, mode)]]
    turns = [a["n_asst"] for a in runs_all]
    inp = [a["input"] / max(a["n_asst"], 1) for a in runs_all]
    out = [a["output"] / max(a["n_asst"], 1) for a in runs_all]
    rea = [a["reasoning"] / max(a["n_asst"], 1) for a in runs_all]
    print(f"{mode:<8}{statistics.mean(turns):>18.2f}{statistics.mean(inp):>18,.0f}{statistics.mean(out):>18,.0f}{statistics.mean(rea):>16,.0f}")

# ---- 6. Per-case detail dump for the two modes of interest ----
print()
print("=" * 100)
print("PER-CASE TOKENS (patch vs pi, all models) — totalTokens")
print("=" * 100)
print(f"{'case':<24}{'model':<6}{'patch':>12}{'pi':>12}{'rows':>12}{'code':>12}{'patch edit calls':>18}{'pi edit calls':>14}")
cases = sorted({a["case"] for mode in MODES for model in ["ds", "sol", "luna", "opus"] for a in data[(model, mode)]})
for case in cases:
    for model in ["ds", "sol", "luna", "opus"]:
        row = {}
        for mode in MODES:
            for a in data[(model, mode)]:
                if a["case"] == case:
                    row[mode] = a
        if not row:
            continue
        def g(mode, key):
            return row[mode][key] if mode in row else float("nan")
        print(f"{case:<24}{model:<6}{g('patch','totalTokens'):>12,.0f}{g('pi','totalTokens'):>12,.0f}{g('rows','totalTokens'):>12,.0f}{g('code','totalTokens'):>12,.0f}{g('patch','edit_calls'):>18}{g('pi','edit_calls'):>14}")
